-- Catalogo de exercicios.
--
-- Rodar UMA vez, em banco novo:
--   psql -U <usuario> -d <banco> -f db/seed.sql
--
-- A ordem das linhas define os id_exercicio — nao reordenar em um banco que ja
-- tem treinos cadastrados, ou os treinos passam a apontar para outro exercicio.

INSERT INTO exercicio (nome_exercicio, tipo) VALUES
    ('SUPINO SENTADO',           'PEITO'),
    ('SUPINO INCLINADO MÁQUINA', 'PEITO'),
    ('SUPINO CONVERGENTE',       'PEITO'),
    ('CRUCIFIXO RETO',           'PEITO'),
    ('CRUCIFIXO INCLINADO',      'PEITO'),
    ('PULL OVER',                'PEITO'),
    ('PEITORAL',                 'PEITO'),
    ('CROSS OVER (CRUCIFIXO)',   'PEITO'),
    ('SUPINO RETO LIVRE',        'PEITO'),
    ('SUPINO INCLINADO LIVRE',   'PEITO'),
    ('SUPINO DECLINADO',         'PEITO'),
    ('FLEXÃO',                   'PEITO'),
    ('ROSCA DIRETA W',           'BÍCEPS'),
    ('ROSCA CONCENTRADA',        'BÍCEPS'),
    ('ROSCA ALTERNADA',          'BÍCEPS'),
    ('MARTELO',                  'BÍCEPS'),
    ('CROSS OVER',               'BÍCEPS'),
    ('BANCO BÍCEPS',             'BÍCEPS'),
    ('BANCO 45°',                'BÍCEPS'),
    ('ENROLAMENTO',              'ANTEBRAÇO'),
    ('FLEXÃO DE PUNHO',          'ANTEBRAÇO'),
    ('EXTENSÃO DE PUNHO',        'ANTEBRAÇO'),
    ('ROSCA INVERSA',            'ANTEBRAÇO'),
    ('DESENVOLVIMENTO MÁQUINA',  'OMBRO/TRAPÉZIO'),
    ('DESENVOLVIMENTO LIVRE',    'OMBRO/TRAPÉZIO'),
    ('ELEVAÇÃO FRONTAL',         'OMBRO/TRAPÉZIO'),
    ('ELEVAÇÃO LATERAL',         'OMBRO/TRAPÉZIO'),
    ('REMADA ALTA',              'OMBRO/TRAPÉZIO'),
    ('ELEVAÇÃO POSTERIOR',       'OMBRO/TRAPÉZIO'),
    ('ARNOLD',                   'OMBRO/TRAPÉZIO'),
    ('ENCOLHIMENTO',             'OMBRO/TRAPÉZIO'),
    ('PARALELAS',                'ABDOMEN'),
    ('ELEVAÇÃO DE PERNA',        'ABDOMEN'),
    ('MÁQUINA',                  'ABDOMEN'),
    ('BANCO DECLINADO',          'ABDOMEN'),
    ('ESTEIRA',                  'CÁRDIO'),
    ('BICICLETA',                'CÁRDIO'),
    ('ELIPTICO',                 'CÁRDIO'),
    ('PUXADOR COSTAS',           'COSTAS'),
    ('PUXADOR FRENTE',           'COSTAS'),
    ('REMADA',                   'COSTAS'),
    ('REMADA UNI LATERAL',       'COSTAS'),
    ('REMADA CURVADA',           'COSTAS'),
    ('DORSAL',                   'COSTAS'),
    ('CRUCIFIXO INVERTIDO',      'COSTAS'),
    ('PULL DOWN',                'COSTAS'),
    ('REMADA CAVALINHO',         'COSTAS'),
    ('EXTENSÃO LOMBAR',          'COSTAS'),
    ('PULLEY',                   'TRÍCEPS'),
    ('TESTA',                    'TRÍCEPS'),
    ('CORDA',                    'TRÍCEPS'),
    ('INVERTIDO',                'TRÍCEPS'),
    ('BANCO',                    'TRÍCEPS'),
    ('FRANCÊS',                  'TRÍCEPS'),
    ('CROSS OVER',               'TRÍCEPS'),
    ('COICE',                    'TRÍCEPS'),
    ('PARALELA',                 'TRÍCEPS'),
    ('AGACHAMENTO LIVRE',        'PERNA'),
    ('AGACHAMENTO BARRA GUIADA', 'PERNA'),
    ('AGACHAMENTO SUMÔ',         'PERNA'),
    ('ADUTOR',                   'PERNA'),
    ('AFUNDO',                   'PERNA'),
    ('EXTENSORA',                'PERNA'),
    ('LEG PRESS 45°',            'PERNA'),
    ('LEG BARRA GUIADA',         'PERNA'),
    ('ELEVAÇÃO DE JOELHO',       'PERNA'),
    ('PANTURRILHA',              'PERNA'),
    ('FLEXORA',                  'POSTERIOR/GLÚTEO'),
    ('POSTERIOR EM PÉ',          'POSTERIOR/GLÚTEO'),
    ('STIFF',                    'POSTERIOR/GLÚTEO'),
    ('ABDUTOR',                  'POSTERIOR/GLÚTEO'),
    ('GLÚTEO 4 APOIOS',          'POSTERIOR/GLÚTEO'),
    ('ELEVAÇÃO DE QUADRIL',      'POSTERIOR/GLÚTEO'),
    ('GLÚTEO CROSS OVER',        'POSTERIOR/GLÚTEO'),
    ('GLÚTEO LEG PRESS',         'POSTERIOR/GLÚTEO'),
    ('GLÚTEO ESPALDAR',          'POSTERIOR/GLÚTEO'),
    ('GLÚTEO BARRA GUIADA',      'POSTERIOR/GLÚTEO'),
    -- Escritos à mão nas fichas, fora do formulário impresso da academia. Vêm
    -- no fim, e não junto do bloco de ABDOMEN, porque a ordem das linhas define
    -- o id_exercicio: inserir no meio deslocaria o id de tudo que vem depois, e
    -- os treinos já cadastrados passariam a apontar para outro exercício.
    ('PRANCHA LATERAL',          'ABDOMEN'),
    ('REMADOR ALTERNADO',        'ABDOMEN');
